### ISSUE TITLE
Mocking not functional with Jest + storybook + storyshots

### ISSUE THREAD

**Issue by intgr** [albertogasparin/react-magnetic-di#10]
Hi, I'm trying to use react-magnetic-di in a project created using https://github.com/facebook/create-react-app along with Jest and storybook snapshots.

For some reason the mocking does not appear to work. Apologies in advance if I have misunderstood something, I do not understand the whole development stack very well.

Is the Babel plugin critical for the functioning of magnetic-di, or is it optional? It seems create-react-app out of the box does not allow custom Babel plugins.

In any case, I tried ejecting from create-react-app and created `babel.config.json` with:
```json
{
  "plugins": [["react-magnetic-di/babel-plugin", {"forceEnable": true}]]
}
```

Here's my test case:
```tsx
import {di, DiProvider} from 'react-magnetic-di';
import React from 'react';

const useBla = () => 'real';

const useBlaMock = di.mock(useBla, () => 'mocked');

const Bla: React.FC = () => {
  di(useBla);
  const value = useBla();
  return <div>{value}</div>;
};

storiesOf('DiTest', module).add('bla', () => (
  <DiProvider use={[useBlaMock]}>
    <Bla />
  </DiProvider>
));
// ^^^^^^^^^^^ test case
```

The snapshot output is:
```
// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`Storyshots DiTest bla 1`] = `
<div>
  real
</div>
`;
```

So the mocked return value of `mocked` was not used.

**Comment by albertogasparin** [comment]
The babel plugin is required for `di` to work. I'm planning to add support to babel macros soon so it can be used with CRA without requiring eject. 

By looking at your code I cannot spot anything wrong. I also checked it with the babel plugin and it gets properly transformed. Is there any error in the console? I'll try to set up a full example with storybooks over the weekend but if you could provide the code that would make my life much easier (either on GitHub or code sandbox).

**Comment by albertogasparin** [comment]
We implemented it our codebase and works as expected. Please update to latest version and try again. If the issue persists, please provide a reproducible scenario.
Thanks
