### ISSUE TITLE
Issues with CRA and TypeScript

### ISSUE THREAD

**Issue by zanonnicola** [albertogasparin/react-magnetic-di#18]
Hi Alberto,

thanks for the project, looks very cool!
I was trying it out on a React app bootstrapped with the TypeScript template and when I import the library like so:

`import { di } from "react-magnetic-di/macro";`

I get: `Cannot find module 'react-magnetic-di/macro' or its corresponding type declarations.`

I guess it makes sense since they seem to be missing when you import it like that.

Anyway, using the library with TS doesn't seems to be working properly for me. 

For example if you include the doc example for testing with RTL it complains about missing required children prop (as per your types):

```tsx
const { container } = render(<MyComponent />, {
    wrapper: (p) => <DiProvider use={[ModalOpenMock, useQueryMock]} {...p} />,
  });
```

Should be:

```tsx
const { container } = render(<MyComponent />, {
    wrapper: (p: {children?: React.ReactNode}) => <DiProvider use={[ModalOpenMock, useQueryMock]}  children={p.children} />,
  });
```

It's just a documentation issue but will probably trip other users.

I wasn't able to run it in the end unfortunately but maybe because of the first error above that results in `Warning: Seems like you are using react-magnetic-di without Babel plugin...` if I import without `/macro` and `Cannot find module 'react-magnetic-di/macro' from '/Users/XXXX/repos/repo/src/components/AdminMessages'` if I add `//@ts-ignore` to it.

Thanks!

**Comment by albertogasparin** [comment]
Thank you for checking it out! 
May I ask you which version you installed? Because the `/macro` plugin support is very recent and only available in `react-magnetic-di@next` (basically I'm still ironing out v2.1.0). I you installed v2.0.1 it will not work.

Fair point on `DiProvider` props. I might make children optional so it won't complain about the types

**Comment by zanonnicola** [comment]
I have installed `v2.0.1`. With `@next` it works fine!

**Comment by albertogasparin** [comment]
v2.1.0 has been published. `react-magnetic-di/macro` is now officially out.
