### ISSUE TITLE
Error: "Invalid hook call. Hooks can only be called inside of the body of a function component."

### ISSUE THREAD

**Issue by pgarciacamou** [albertogasparin/react-magnetic-di#38]
I'm seeing the following error whenever I use `<DiProvider />` inside `jest`:

```
Invalid hook call. Hooks can only be called inside of the body of a function component.
```

<img width="950" alt="Screen Shot 2021-11-16 at 5 02 59 PM" src="https://user-images.githubusercontent.com/8354571/142090493-3f1ba4c4-a028-4b1c-a457-c1875c2ebcfe.png">

<img width="964" alt="Screen Shot 2021-11-16 at 5 04 52 PM" src="https://user-images.githubusercontent.com/8354571/142090646-7398dac2-23a8-4dfe-af91-88725db70fdd.png">

I thought I was doing something wrong but I tried this by building an MVP:

```jsx
// jest spec
// SomeTest.spec.js
import { useState } from 'react'
import { DiProvider, di, injectable } from 'react-magnetic-di'
import { render } from '@testing-library/react'
import '@testing-library/jest-dom'

function useSomeHook() {
  return useState('dummy')
}

function Testing() {
  di(useSomeHook)
  const [dummy] = useSomeHook()
  return <div>{dummy}</div>
}

const useSomeHookDi = injectable(useSomeHook, () => ['testing'])
function WithDep() {
  return (
    <DiProvider use={[useSomeHookDi]}>
      <Testing />
    </DiProvider>
  )
}

test('loads and displays input text', async () => {
  const { getByText } = render(<WithDep />)
  expect(() => getByText('testing')).not.toThrow()
})
```

**Comment by albertogasparin** [comment]
Have you configured the babel plugin for your tests too?
As if I copy your MVP [in the tests example](https://github.com/albertogasparin/react-magnetic-di/blob/c9ecaebd77edd660aabd07d1dc74d7ec3a1feac0/examples/flow/components/__tests__/input-testinglib.test.js) I can see it pass properly.
