### ISSUE TITLE
unable to `di` in production mode

### ISSUE THREAD

**Issue by hkar19** [albertogasparin/react-magnetic-di#42]
Hi, thank you for this amazing work!

I want to do dependency injection on production mode (as for mocking data, for now), and i have added these lines in my `.babelrc`
```json
plugins: [
    ["react-magnetic-di/babel-plugin", { "forceEnable": true }],
  ],
```

the problem was in production mode, `di` was not applied. And if it helps, i cannot import things from `react-magnetic-di` even after i put those line above in my `.babelrc`.

is there something i did miss?

Thank you.

**Comment by hkar19** [comment]
btw i am using CRA that has macros built-in. how do i `forceEnable`?

**Comment by albertogasparin** [comment]
Thanks for pointing it out, I've updated the readme
