### ISSUE TITLE
Is it possible to use di() in parent components only?

### ISSUE THREAD

**Issue by cattrn** [albertogasparin/react-magnetic-di#46]
Hi there, loving this package, thank you! I have a question - am I right in assuming this sentence here means that you can make the `di()` call in a parent component and it will replace all usages in child components?

> In the example above we replace all `Modal` and `useQuery` dependencies across all components in the tree with the custom versions.

I'm trying to create a wrapper component for storybook so that all the di code can be contained in the story itself, and am testing this in a wrapper component, but am thinking I might've misinterpreted the sentence above. For example, this is my storybook for the component.

```js
// Header.stories.jsx
import { useState } from "react";
import { DiProvider, injectable } from "react-magnetic-di";
import Header from "./Header";

const useStateDi = injectable(useState, () => ["hello", () => null]);

export default {
  title: "My Components/Header",
  component: Header,
};

const Template = () => (
  <DiProvider use={[useStateDi]}>
    <Header />
  </DiProvider>
);

export const Default = Template.bind({});
```

And then, in my actual component, if I'm looking to replace useState for example, can I call `di(useState)` in a component that wraps the actual `useState` usage?

```js
import { useState } from "react";
import { di } from "react-magnetic-di";

const ChildComponent = () => {
  const [title, _setTitle] = useState("Hi there");
  return <h2>{title}</h2>;
};

const Header = () => {
  di(useState);
  return <ChildComponent />;
};

export default Header;
```

**Comment by albertogasparin** [comment]
Thanks! About your question, the answer is not quite. Each component needs to have `di` called with the dependencies you’d like to replace, as that signals where you want the substitution to happen.
So you cannot just `di` once, in the top component, as it will not know which setState to replace. The correct code is:

```jsx
const ChildComponent = () => {
  di(useState);
  const [title, _setTitle] = useState("Hi there");
  return <h2>{title}</h2>;
};
```

Basically the `di` call needs to be in all your “real” components code for the system to work. That is why we developed a babel plugin to strip that code on production builds (so it does not affect performance) and also Eslint rules to help automate adding `di` calls for all dependencies

**Comment by cattrn** [comment]
Sorry for the massively delayed response. You're a champion, thank you for responding to this so quickly!
