### ISSUE TITLE
Unbound Magnetic from React

### ISSUE THREAD

**Issue by theKashey** [albertogasparin/react-magnetic-di#68]
Magnetic is mostly used in a _preconfigured_ testing environment with so many things expected to be "global". Having this in mind  what would one think about adding alternative way to configure `di` - via global configuration, not ContextApi

That will allow using `di` for plain functions, not components/hooks. One can do (and doing) this today by testing such functions as hooks, which is not the correct way.

All required is to wire a configuration variable to https://github.com/albertogasparin/react-magnetic-di/blob/master/src/react/consumer.js#L14

**Comment by albertogasparin** [comment]
Implemented via `runWithDi(() => fn(), deps)`
