### ISSUE TITLE
DiProvider with global does not clean replacementMap on error

### ISSUE THREAD

**Issue by albertogasparin** [albertogasparin/react-magnetic-di#88]
Whenever `<DiProvider global />` is used and the tree throws an error, we skip the unmount use effect and replacements between tests are not cleared.

We should convert DiProvider to a class and add `componentDidCatch` to call `globalDi.clear()`

**Comment by theKashey** [comment]
This is one way to solve the problem, another way is to enforce cleanup between tests:
- it can be a build in feature, like in testing library
- or it can be enforced as _mounting global DiProvider with another global DiProvider being "present" leads to an error_
  - this variant should account for nested DiProviders, which is "ok" case

**Comment by albertogasparin** [comment]
Yes, might eventually go down that path. For now my worry was with tests and storybooks blowing up and then leaks would happen

**Comment by theKashey** [comment]
:fingerguns: we definitely missing this sort of cleanup for storybook and tests
