### ISSUE TITLE
Is storybook 7 supported?

### ISSUE THREAD

**Issue by DenisQC** [albertogasparin/react-magnetic-di#90]
I have a sneaky suspicion that I might be doing something wrong, but I copy/pasted the examples on the readme and shooting `console.log(debug(ModalOpenDi));` seems to always come back with `undefined`. I am using react native and storybook 7, so I wonder if maybe my setup is not supported somehow?

**Comment by theKashey** [comment]
Storybook has no effect of functionality of magnetic, it’s all Babel magic. 
Have you configured Babel plugin?
